/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GovernanceToken } from "./GovernanceToken";
export * as factories from "./factories";
export { GovernanceToken__factory } from "./factories/GovernanceToken__factory";
