/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GovernorContract } from "./GovernorContract";
export * as factories from "./factories";
export { GovernorContract__factory } from "./factories/GovernorContract__factory";
