import { LessonSection } from "../../../types/types";

const tests1: LessonTest = {
  section: LessonSection.adjective,
  unit: 1,
  questions: [
    {
      id: 0,
      question: "Big dog",
      answer: "大きい犬",
      datas: [
        { data: { word: "大きい" } },
        { data: { word: "犬" } },
        { data: { word: "高い", dummy: true } },
        { data: { word: "猫", dummy: true } },
      ],
    },
    {
      id: 1,
      question: "Beautiful flower",
      answer: "美しい花",
      datas: [
        { data: { word: "美しい" } },
        { data: { word: "花" } },
        { data: { word: "穏やかな", dummy: true } },
        { data: { word: "草", dummy: true } },
      ],
    },
    {
      id: 2,
      question: "Famous person",
      answer: "有名な人",
      datas: [
        { data: { word: "有名な" } },
        { data: { word: "人" } },
        { data: { word: "好きな", dummy: true } },
        { data: { word: "動物", dummy: true } },
      ],
    },
    {
      id: 3,
      question: "Silent lake",
      answer: "静かな湖",
      datas: [
        { data: { word: "静かな" } },
        { data: { word: "湖" } },
        { data: { word: "穏やかな", dummy: true } },
        { data: { word: "海", dummy: true } },
      ],
    },
    {
      id: 4,
      question: "Slow train",
      answer: "遅い電車",
      datas: [
        { data: { word: "遅い" } },
        { data: { word: "電車" } },
        { data: { word: "速い", dummy: true } },
        { data: { word: "車", dummy: true } },
      ],
    },
    {
      id: 5,
      question: "Beautiful yard in front of the house",
      answer: "美しい家のまえの庭",
      datas: [
        { data: { word: "美しい" } },
        { data: { word: "家の" } },
        { data: { word: "前の" } },
        { data: { word: "庭" } },
        { data: { word: "汚い", dummy: true } },
        { data: { word: "後ろの", dummy: true } },
        { data: { word: "道路", dummy: true } },
      ],
    },
    {
      id: 6,
      question: "Cool lion in the zoo",
      answer: "かっこいい動物園のライオン",
      datas: [
        { data: { word: "かっこいい" } },
        { data: { word: "動物園" } },
        { data: { word: "の" } },
        { data: { word: "ライオン" } },
        { data: { word: "強い", dummy: true } },
        { data: { word: "が", dummy: true } },
      ],
    },
    {
      id: 7,
      question: "Convenient store infront of the station",
      answer: "便利な駅前の店",
      datas: [
        { data: { word: "便利な" } },
        { data: { word: "駅前の" } },
        { data: { word: "店" } },
        { data: { word: "綺麗な", dummy: true } },
        { data: { word: "駅下の", dummy: true } },
        { data: { word: "会社", dummy: true } },
      ],
    },
    {
      id: 8,
      question: "New that car",
      answer: "新しいあの車",
      datas: [
        { data: { word: "新しい" } },
        { data: { word: "あの" } },
        { data: { word: "車" } },
        { data: { word: "古い", dummy: true } },
        { data: { word: "この", dummy: true } },
        { data: { word: "自転車", dummy: true } },
      ],
    },
    {
      id: 9,
      question: "Desirable ramen my mother cooks",
      answer: "好きな母が作るラーメン",
      datas: [
        { data: { word: "好きな" } },
        { data: { word: "母" } },
        { data: { word: "が" } },
        { data: { word: "作る" } },
        { data: { word: "ラーメン" } },
        { data: { word: "嫌いな", dummy: true } },
        { data: { word: "に", dummy: true } },
        { data: { word: "買う", dummy: true } },
      ],
    },
  ],
};

const tests2: LessonTest = {
  section: LessonSection.adjective,
  unit: 2,
  questions: [
    {
      id: 0,
      orderText: "Change the text below to past tense",
      question: "大きい家",
      answer: "大きかった家",
      datas: [
        { data: { word: "大きかった" } },
        { data: { word: "家" } },
        { data: { word: "大きくない", dummy: true } },
        { data: { word: "大きくなかった", dummy: true } },
      ],
    },
    {
      id: 1,
      orderText: "Change the text below to negative tense",
      question: "親切な友達",
      answer: "親切じゃない友達",
      datas: [
        { data: { word: "親切じゃない" } },
        { data: { word: "友達" } },
        { data: { word: "親切じゃなかった", dummy: true } },
        { data: { word: "親切だった", dummy: true } },
      ],
    },
    {
      id: 2,
      orderText: "Change the text below to negative past tense",
      question: "大切な物",
      answer: "大切じゃなかった物",
      datas: [
        { data: { word: "大切じゃなかった" } },
        { data: { word: "物" } },
        { data: { word: "大切じゃない", dummy: true } },
        { data: { word: "大切ない", dummy: true } },
      ],
    },
    {
      id: 3,
      orderText: "Change the text below to present tense",
      question: "寒くない国",
      answer: "寒い国",
      datas: [
        { data: { word: "寒い" } },
        { data: { word: "国" } },
        { data: { word: "寒かった", dummy: true } },
        { data: { word: "寒な", dummy: true } },
      ],
    },
    {
      id: 4,
      orderText: "Change the text below to negative tense",
      question: "丁寧な店員",
      answer: "丁寧ではない店員",
      datas: [
        { data: { word: "丁寧ではない" } },
        { data: { word: "店員" } },
        { data: { word: "丁寧くない", dummy: true } },
        { data: { word: "丁寧がない", dummy: true } },
      ],
    },
    {
      id: 5,
      orderText: "Change the text below to past tense",
      question: "必要な書類",
      answer: "必要だった書類",
      datas: [
        { data: { word: "必要だった" } },
        { data: { word: "書類" } },
        { data: { word: "必要でった", dummy: true } },
        { data: { word: "必要だ", dummy: true } },
        { data: { word: "必要した", dummy: true } },
      ],
    },
    {
      id: 6,
      orderText: "Change the text below to negative past tense",
      question: "優しい先生",
      answer: "優しくなかった先生",
      datas: [
        { data: { word: "優しくなかった" } },
        { data: { word: "先生" } },
        { data: { word: "優しいなかった", dummy: true } },
        { data: { word: "優しいでなかった", dummy: true } },
      ],
    },
    {
      id: 7,
      orderText: "Change the text below to present tense",
      question: "忙しくなかった時間帯",
      answer: "忙しい時間帯",
      datas: [
        { data: { word: "忙しい" } },
        { data: { word: "時間帯" } },
        { data: { word: "忙しな", dummy: true } },
        { data: { word: "忙しく", dummy: true } },
      ],
    },
    {
      id: 8,
      orderText: "Change the text below to negative tense",
      question: "下手な運転手",
      answer: "下手じゃない運転手",
      datas: [
        { data: { word: "下手" } },
        { data: { word: "じゃない" } },
        { data: { word: "運転手" } },
        { data: { word: "くない", dummy: true } },
        { data: { word: "ない", dummy: true } },
        { data: { word: "しない", dummy: true } },
      ],
    },
    {
      id: 9,
      orderText: "Change the text below to past tense",
      question: "弱い格闘家",
      answer: "弱かった格闘家",
      datas: [
        { data: { word: "弱" } },
        { data: { word: "かった" } },
        { data: { word: "格闘家" } },
        { data: { word: "かだった", dummy: true } },
        { data: { word: "だった", dummy: true } },
        { data: { word: "くかった", dummy: true } },
      ],
    },
  ],
};

const tests3: LessonTest = {
  section: LessonSection.adjective,
  unit: 3,
  questions: [
    {
      id: 0,
      orderText: "Translate the text below to English",
      question: "富士山の方が筑波山より高い",
      answer: "Mt.FujiishigherthanMt.Tsukuba",
      answerForView: "Mt.Fuji is higher than Mt.Tsukuba",
      datas: [
        { data: { word: "Mt.Fuji" } },
        { data: { word: "is" } },
        { data: { word: "higher" } },
        { data: { word: "than" } },
        { data: { word: "Mt.Tsukuba" } },
        { data: { word: "bigger", dummy: true } },
        { data: { word: "of", dummy: true } },
      ],
    },
    {
      id: 1,
      orderText: "Translate the text below to Japanese",
      question: "Mt.Fuji is more higher than Mt.Tsukuba",
      answer: "筑波山より富士山の方が高い",
      datas: [
        { data: { word: "筑波山" } },
        { data: { word: "より" } },
        { data: { word: "富士山" } },
        { data: { word: "の" } },
        { data: { word: "方が" } },
        { data: { word: "高い" } },
        { data: { word: "に", dummy: true } },
        { data: { word: "一番", dummy: true } },
      ],
    },
    {
      id: 2,
      orderText: "Change the text below to comparative sentence(than 猫)",
      question: "人気な犬",
      answer: "猫と比べて犬の方が人気",
      datas: [
        { data: { word: "猫" } },
        { data: { word: "と" } },
        { data: { word: "比べて" } },
        { data: { word: "犬" } },
        { data: { word: "の" } },
        { data: { word: "方が" } },
        { data: { word: "人気" } },
      ],
    },
    {
      id: 3,
      orderText: "Translate the text below to English",
      question: "富士山は山で一番高いです",
      answer: "Mt.Fujiisthehighestinthemountains",
      answerForView: "Mt.Fuji is the highest in the mountains",
      datas: [
        { data: { word: "Mt.Fuji" } },
        { data: { word: "is" } },
        { data: { word: "the" } },
        { data: { word: "highest" } },
        { data: { word: "in" } },
        { data: { word: "the" } },
        { data: { word: "mountains" } },
        { data: { word: "higher", dummy: true } },
        { data: { word: "are", dummy: true } },
      ],
    },
    {
      id: 4,
      orderText: "Translate the text below to Japanese",
      question: "Mt.Fuji is the highest in the mountains.",
      answer: "富士山は山で最も高い",
      datas: [
        { data: { word: "富士山" } },
        { data: { word: "は" } },
        { data: { word: "山" } },
        { data: { word: "で" } },
        { data: { word: "最も" } },
        { data: { word: "高い" } },
        { data: { word: "に", dummy: true } },
        { data: { word: "より", dummy: true } },
      ],
    },
    {
      id: 5,
      orderText: "Change the text below to superlative sentence(動物で)",
      question: "可愛い犬",
      answer: "犬が動物で最も可愛い",
      datas: [
        { data: { word: "犬" } },
        { data: { word: "が" } },
        { data: { word: "動物" } },
        { data: { word: "で" } },
        { data: { word: "最も" } },
        { data: { word: "可愛い" } },
      ],
    },
    /*{
      id: 6,
      orderText: "Change the text below to negative past tense",
      question: "優しい先生",
      answer: "優しくなかった先生",
      datas: [
        { data: { word: "優しくなかった" } },
        { data: { word: "先生" } },
        { data: { word: "優しいなかった", dummy: true } },
        { data: { word: "優しいでなかった", dummy: true } },
      ],
    },
    {
      id: 7,
      orderText: "Change the text below to present tense",
      question: "忙しくなかった時間帯",
      answer: "忙しい時間帯",
      datas: [
        { data: { word: "忙しい" } },
        { data: { word: "時間帯" } },
        { data: { word: "忙しな", dummy: true } },
        { data: { word: "忙しく", dummy: true } },
      ],
    },
    {
      id: 8,
      orderText: "Change the text below to negative tense",
      question: "下手な運転手",
      answer: "下手じゃない運転手",
      datas: [
        { data: { word: "下手" } },
        { data: { word: "じゃない" } },
        { data: { word: "運転手" } },
        { data: { word: "くない", dummy: true } },
        { data: { word: "ない", dummy: true } },
        { data: { word: "しない", dummy: true } },
      ],
    },
    {
      id: 9,
      orderText: "Change the text below to past tense",
      question: "弱い格闘家",
      answer: "弱かった格闘家",
      datas: [
        { data: { word: "弱" } },
        { data: { word: "かった" } },
        { data: { word: "格闘家" } },
        { data: { word: "かだった", dummy: true } },
        { data: { word: "だった", dummy: true } },
        { data: { word: "くかった", dummy: true } },
      ],
    },*/
  ],
};

const tests = [tests1, tests2, tests3];
export default tests;
